apiVersion: v1
kind: Service
metadata:
  labels:
    app: td2311-myapp
  name: td2311-myapp
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: td2311-myapp
  type: LoadBalancer
