apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: td2311-myapp
  name: td2311-myapp
spec:
  selector:
    matchLabels:
      app: td2311-myapp
  template:
    metadata:
      labels:
        app: td2311-myapp
    spec:
      containers:
        - image: ghcr.io/mollso/td2311-myapp-po:latest
          name: td2311-myapp
          ports:
            - containerPort: 8080
          env:
            - name: POD
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              memory: "64Mi"
            limits:
              memory: "1200Mi"
